### ISSUE TITLE
DataItem created from DataItem.FromAddress() fail to write with error 5 in branch: development

### ISSUE THREAD

**Issue by bauerju** [S7NetPlus/s7netplus#168]
Hi
I'm testing latest development branch:  
I created a bunch of DataItems with `DataItem.FromAddress(string)`. 

Writing with `Write(DataItem[])` fails with Exception:  
> Write failed for 3 items. See the innerExceptions for details.

InnerException is

> Write of dataItem S7.Net.Types.DataItem failed with error code 5.

Problem seems to be the BitAdr of the DataItems.
It is converted from the result of bitnumber -1 in `PLCAddress.Parse` to 255 in DataItem.BitAdr.
If I manually set this to 0 for all VarTypes excluding Bit. then the write gives no error.

Jürgen

**Comment by mycroes** [comment]
Hi @bauerju Thanks again for reporting. The bug is related to issue #150 as well because proper (standardized) defaults for `bitAdr` could have prevented this issue. I committed a fix in #169. As far as I could see this works fine now, but I would appreciate if you could test as well. Also, feel free to review the code (you can actually use the GitHub review process for that).
