### ISSUE TITLE
Reading counters and timers

### ISSUE THREAD

**Issue by emarinirc** [S7NetPlus/s7netplus#247]
Hi, 
I try to read counters (C0...C255) and timers (T0...T255) in S7200 and S7300 but throw an error 
"Error WrongNumberReceivedBytes".

The rest of Variables reads them correctly.

**Comment by FalcoGoodbody** [comment]
Hi @emarinirc ,

there was an update of this library some days ago (0.7.0) which includes some major upgrade in the TCP-communication.
Maybe you can give it a try retest with this version?

**Comment by mycroes** [comment]
Closing due to missing feedback, feel free to reopen.

**Comment by MO2k4** [comment]
@mycroes This still seems to be an issue, especially when retrieving multiple counters in one request.

```csharp
var readMultipleVarsAsync = await plc.ReadMultipleVarsAsync([
            new DataItem
            {
                DataType = DataType.Counter,
                DB = 0,
                StartByteAdr = 0,
                Count = 1,
                VarType = VarType.Counter
            },
            new DataItem
            {
                DataType = DataType.Counter,
                DB = 1,
                StartByteAdr = 0,
                Count = 1,
                VarType = VarType.Counter
            }
        ]);
```

Which leads to this payload response:

<img width="175" height="805" alt="Image" src="https://github.com/user-attachments/assets/fef317ae-0e2c-4c6c-b1a7-0505aa97155f" />

For me it looks like the bytes 17 and 25 specify the length of the data value, but the calculation for the length returns 2 bytes for a counter value. 

While retrieving the values, on the first value everything is ok, but on the secondary value a WrongNumberReceicedBytes Exception is thrown after checking for a success return code, which also is invalid from my point of view. The exception gets thrown because the offset is not calculated correctly.
